[package]
name = "randomness"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rand.workspace = true
rand_distr.workspace = true
